from __future__ import annotations

from typing import Protocol

from recall.models import Chunk, LexicalRanker, SearchResult, Stats


class Store(Protocol):
    def init(self, dim: int, model: str, provider: str) -> None: ...
    def upsert(self, chunks: list[Chunk]) -> None: ...
    def delete_source(self, tag: str) -> None: ...
    def prune(self, tag: str, seen: set[str]) -> int: ...
    def search(
        self, qvec: list[float], qtext: str, sources: list[str], limit: int, k: int
    ) -> SearchResult: ...
    def lexical_ranker(self) -> LexicalRanker: ...
    def stats(self) -> Stats: ...
